eeeee/eeeee/urls.py
from django.contrib import admin
from django.urls import include, path
#from . import views

urlpatterns = [
    path('', include('user.urls')),
    path('instructor/', include('instructor.urls')),
    path('student/', include('student.urls')),
    path('ta/', include('ta.urls')),
    path('admin/', admin.site.urls),
]

eeeee/instructor/urls.py
from django.urls import include,path

from . import views

urlpatterns = [
	path('login/',views.login,name='login_instructor'),
	path('newinstructor/',views.newinstructor,name='newinstructor'),
    path('', views.index),
    path('logout/',views.logout),
    path('new_subjective_exam',views.new_subjective_exam,name='new_subjective_exam'),
    path('new_exam',views.new_exam,name='new_exam'),
    path('edit_exam/<int:exam_id>',views.edit_exam,name='edit_exam'),
    path('edit_question/<int:question_id>',views.edit_question,name='edit_question'),
    path('new_question/<int:exam_id>',views.new_question,name='new_question'),
    path('new_question_from_db/<int:exam_id>/<int:question_bank_qid>',views.new_question_from_db,name='new_question_from_db'),
    path('exam/<int:exam_id>',views.show_exam,name='show_exam'),
    path('topic_select/<int:exam_id>',views.ts,name='qb'),
    path('qb/<int:exam_id>',views.qb,name='qb'),
    path('look_questions/<int:topic_id>',views.show_questions_in_topic,name='show_questions_in_topic'),
    path('topics_in_qb/',views.topics_in_qb,name='topics_in_qb'), # new_question_from_d
    path('<int:exam_id>/subm_results',views.subm_results,name='subm_results'),
]

eeeee/student/urls.py
from django.urls import include,path

from . import views

urlpatterns = [
	path('login/',views.login,name='login_student'),
	path('newstudent/',views.newstudent,name='newstudent'),
	path('', views.index),
	path('exam_paper/<int:exam_id>',views.take_exam,name='take_exam'),
	path('completed_paper/<int:exam_id>',views.completed_exam,name='completed_exam'),
	path('view_exam/<int:eid>/<int:uid>', views.questions),
    path('question/<int:eid>/<int:uid>/<int:index>', views.show_question),
]

eeeee/ta/urls.py
from django.urls import include,path

from . import views
from student import views as std_views

urlpatterns = [
	path('login/',views.login,name='login_ta'),
    path('', views.index),
    path('newta/',std_views.newta),
    path('exam/<int:exam_id>', views.exam_students),
    path('correct_exam/<int:eid>/<int:uid>', views.questions),
    path('question/<int:eid>/<int:uid>/<int:index>', views.show_question),
]

eeeee/instructor/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from user.models import Courses, User as Instructor
from datetime import datetime

class Exam(models.Model):
    name = models.CharField(max_length=200)
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    start_time = models.DateTimeField(default=datetime.now())
    end_time = models.DateTimeField(default=datetime.now())
    max_marks = models.IntegerField(default = 0)
    def __str__(self):
        return self.name

class SubjectiveExam(models.Model):
    name = models.CharField(max_length=200)
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    qno = models.IntegerField()
    def __str__(self):
        return self.name

class SubjectiveExamTaken(models.Model):
    exam = models.ForeignKey(SubjectiveExam, on_delete=models.CASCADE)
    q_index = models.IntegerField(default = 0)
    user = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    marks = models.IntegerField(default=0)
    remarks = models.TextField(null=True)
    corrected_by = models.ForeignKey(Instructor, on_delete=models.CASCADE, null=True, related_name='+')
    def __str__(self):
        return "Answer for question " + str(self.q_index)

class Topic(models.Model):
    course=models.ForeignKey(Courses,on_delete=models.CASCADE)
    topic_name=models.CharField(max_length=200)
    def __str__(self):
        return self.topic_name

class Question(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=500)
    choice1 = models.CharField(max_length=200)
    choice2 = models.CharField(max_length=200)
    choice3 = models.CharField(max_length=200)
    positive_marks = models.IntegerField(default = 3)
    negative_marks = models.IntegerField(default = -1)
    answer = models.IntegerField()

class Question_Bank(models.Model):
    department = models.CharField(max_length=200)
    course=models.ForeignKey(Courses,on_delete=models.CASCADE)
    topic=models.ForeignKey(Topic, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=500)
    choice1 = models.CharField(max_length=200)
    choice2 = models.CharField(max_length=200)
    choice3 = models.CharField(max_length=200)
    answer = models.IntegerField()
    def __str__(self):
        return "QB: "+str(self.topic)+": "+str(self.question_text)

eeeee/instructor/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .forms import NewExamForm, NewQuestionForm, NewInstructorForm, NewTopicForm, NewQuestionInQBForm, NewSubExamForm
from user.forms import LoginForm
from django.shortcuts import render
from user.models import User as Instructor
from student.models import ExamTaken,Answer
from .models import Exam, Question, Topic, Question_Bank, SubjectiveExamTaken, SubjectiveExamTaken, SubjectiveExam
import operator


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = form.data['username']
        password = form.data['password']
        instructor = Instructor.objects.all().filter(username = username).filter(password = password)
        # user = Instructor.authenticate(request, username=username, password=password)
        if form.is_valid():
            if len(instructor)==0 :
                return render(request, 'instructor_login.html', {'form': form})
            else:
                request.session['username'] = username
                return HttpResponseRedirect('/instructor')
    else:
        form = LoginForm()
    return render(request, 'instructor_login.html', {'form': form})

def subm_results(request, exam_id):
    username = request.session['username']
    instructor = Instructor.objects.get(username = username)
    exam = Exam.objects.get(id=exam_id)
    instructor = exam.instructor
    instr_course= instructor.course
    student_set = Instructor.objects.all().filter(is_student=True, is_instructor=False, course=instr_course)
    examtaken_set = ExamTaken.objects.all().filter(exam__id=exam_id).order_by('marks_obtained')[:30]
    print(student_set)
    print(examtaken_set)
    return render(request, 'subm_results.html', {'examtaken_set':examtaken_set})    


def new_subjective_exam(request):
    instructor = request.session['username']
    if request.method == 'POST':
        form = NewSubExamForm(request.POST)
        if form.is_valid():
            exam = form.save(commit=False)
            exam.instructor = Instructor.objects.get(username = instructor)
            exam.save()
            r = exam.qno+1
            s = Instructor.objects.all().filter(is_student = True).filter(course = exam.instructor.course)
            for x in range(1, r):
                for student in s:
                    SubjectiveExamTaken.objects.create(user = student, q_index = x, exam = exam)
            return HttpResponseRedirect('/instructor')
        else:
            return render(request, 'new_exam.html', {'form': form})
            

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NewSubExamForm()

    return render(request, 'new_exam.html', {'form': form})


def newinstructor(request):
    if request.method == 'POST':
        form = NewInstructorForm(request.POST)
        username=form.data['username']
        if form.is_valid():
            newinstr=form.save(commit = False)
            newinstr.is_student = False
            newinstr.is_instructor = True
            newinstr.save()
            request.session['username'] = newinstr.username
            return HttpResponseRedirect('/instructor/login')
    else:
        form = NewInstructorForm()
    return render(request, 'newinstructor.html', {'form': form})

def index(request):
    username = request.session['username']
    instructor = Instructor.objects.get(username = username)
    exams_set = Exam.objects.filter(instructor = instructor)
    exams_set1 = SubjectiveExam.objects.filter(instructor__course = instructor.course)
    return render(request, 'instructor.html', {'instructor': instructor, 'exams_set':exams_set, 'exams_set2':exams_set1})

def new_exam(request):
    instructor = request.session['username']

    if request.method == 'POST':
        form = NewExamForm(request.POST)
        
        if form.is_valid():
            exam = form.save(commit=False)
            exam.instructor = Instructor.objects.get(username = instructor)
            exam.save()
            id = exam.id
            return HttpResponseRedirect('/instructor/new_question/'+str(id))
        else:
        	return render(request, 'new_exam.html', {'form': form})
    else:
        form = NewExamForm()

    return render(request, 'new_exam.html', {'form': form})

def edit_exam(request, exam_id):
	exam = Exam.objects.get(pk = exam_id)
	if request.method == 'POST':
		form = NewExamForm(request.POST, instance=exam)
		if form.is_valid():
			exam = form.save(commit=False)
			exam.save()
			id = exam.id
			return HttpResponseRedirect('/instructor/exam/'+str(id))
		else:
			return render(request, 'edit_exam.html', {'form': form})
	else:
		form = NewExamForm(instance=exam)
	return render(request, 'edit_exam.html', {'form': form, 'exam_id':exam_id})

def edit_question(request, question_id):
	q = Question.objects.get(pk = question_id)
	if request.method == 'POST':
		form = NewQuestionForm(request.POST, instance=q)
		if form.is_valid():
			question = form.save(commit=False)
			question.save()
			return HttpResponseRedirect('/instructor/exam/'+str(q.exam.id))
		else:
			return render(request, 'edit_question.html', {'form': form})
	else:
		form = NewQuestionForm(instance=q)
	return render(request, 'edit_question.html', {'form': form})



def new_question(request, exam_id):
    instructor = request.session['username']

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NewQuestionForm(request.POST)
        
        if form.is_valid():
            exam = form.save(commit=False)
            exam.exam = Exam.objects.get(id = exam_id)
            ee = Exam.objects.get(id = exam_id)
            exam.save()
            if "continue" in request.POST:
            	return HttpResponseRedirect('/instructor/new_question/'+str(exam_id))
            else :
                q_set = Question.objects.filter(exam__id = exam_id)
                x = 0
                for i in q_set:
                    x = x + i.positive_marks
                ee.max_marks=x
                ee.save()
                return HttpResponseRedirect('/instructor')
        else:
        	return render(request, 'new_question.html', {'form': form})
    else:
        form = NewQuestionForm()

    return render(request, 'new_question.html', {'form': form, 'exam_id':exam_id})

def show_exam(request, exam_id):
	exam = Exam.objects.get(id=exam_id)
	questions_set = Question.objects.filter(exam=exam)
	print(questions_set[0].question_text)
	return render(request, 'show_exam.html', {'questions_set':questions_set, 'exam':exam})

def topics_in_qb(request):
    username = request.session['username']
    instructor = Instructor.objects.get(username = username)
    course = instructor.course
    topics_set = Topic.objects.filter(course = instructor.course)
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.course = course
            topic.save()
            return HttpResponseRedirect('/instructor/topics_in_qb')
        else:
            return HttpResponseRedirect('/instructor/topics_in_qb')
    else:
        form = NewTopicForm()
        return render(request, 'topics_in_qb.html', {'form':form,'instructor': instructor, 'topics_set':topics_set})

def show_questions_in_topic(request, topic_id):
    username = request.session['username']
    instructor = Instructor.objects.get(username = username)
    topic = Topic.objects.get(id = topic_id)
    course = instructor.course
    department = course.department
    questions_set = Question_Bank.objects.filter(topic__id = topic_id)
    if request.method == 'POST':
        form = NewQuestionInQBForm(request.POST)
        if form.is_valid():
            new_q = form.save(commit=False)
            new_q.course = course
            new_q.topic = topic
            new_q.department=department
            new_q.save()
            return HttpResponseRedirect('/instructor/look_questions/'+str(topic_id))
        else:
            return HttpResponseRedirect('/instructor/look_questions/'+str(topic_id))
    else:
        form = NewQuestionInQBForm()
        return render(request, 'show_questions_in_topic.html', {'form':form,'topic':topic, 'questions_set':questions_set})

def logout(request):
    try:
        username = request.session['username']
        request.session.flush()

    except KeyError:
        pass
    return HttpResponseRedirect('/')

def new_question_from_db(request, exam_id, question_bank_qid):
    instructor = request.session['username']
    e = Exam.objects.get(id = exam_id)
    if request.method == 'POST':
        form = NewQuestionForm(request.POST)
        if form.is_valid():
            exam1 = form.save(commit=False)
            exam1.exam = Exam.objects.get(id = exam_id)
            ee = Exam.objects.get(id = exam_id)
            #exam1.save()
            if "continue" in request.POST:
                return HttpResponseRedirect('/instructor/new_question/'+str(exam_id))
            else :
                q_set = Question.objects.filter(exam__id = exam_id)
                x = 0
                for i in q_set:
                    x = x + i.positive_marks
                ee.max_marks=x
                ee.save()
                return HttpResponseRedirect('/instructor')
        else:
            return render(request, 'new_question.html', {'form': form})
            

    # if a GET (or any other method) we'll create a blank form
    else:
        q = Question_Bank.objects.get(id = question_bank_qid)
        question = Question.objects.create(exam=e,question_text=q.question_text,choice1=q.choice1,choice2=q.choice2,choice3=q.choice3,answer=q.answer)
        form = NewQuestionForm(instance=question)

    return render(request, 'new_question.html', {'form': form})

def qb(request, exam_id):
    username = request.session['username']

eeeee/ta/views.py
from django.shortcuts import render, HttpResponseRedirect
from user.forms import LoginForm
from user.models import User as TA
from instructor.models import Exam, Question, SubjectiveExam, SubjectiveExamTaken
from student.models import ExamTaken
from instructor.forms import SubjectiveExamTakenForm

# Create your views here.

def login(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        print('here1')
        # create a form instance and populate it with data from the request:
        form = LoginForm(request.POST)
        username = form.data['username']
        password = form.data['password']
        instructor = TA.objects.all().filter(username = username).filter(password = password)
        # user = Instructor.authenticate(request, username=username, password=password)
        if form.is_valid():
            if len(instructor)==0 :
                print('here2')
                return render(request, 'ta_login.html', {'form': form})
            else:
                request.session['username'] = username
                return HttpResponseRedirect('/ta')
    else:
        form = LoginForm()
    return render(request, 'ta_login.html', {'form': form})


def index(request):
	username = request.session['username']
	ta = TA.objects.get(username = username)
	exams_set =  SubjectiveExam.objects.all().filter(instructor__course = ta.course)
	return render(request, 'ta.html', {'ta': ta, 'exams_set':exams_set})

def exam_students(request, exam_id):
    username = request.session['username']
    ta = TA.objects.get(username = username)
    es = SubjectiveExam.objects.get(id = exam_id)
    es = TA.objects.all().filter(is_student = True).filter(course = es.instructor.course)
    return render(request, 'exam_students.html', {'es':es, 'exam_id':exam_id})

def questions(request, eid, uid):
    q = SubjectiveExamTaken.objects.all().filter(exam__id = eid, user__id = uid).order_by('q_index')
    return render(request, 'questions.html', {'q':q})

def show_question(request,eid,uid,index):
    x = "http://10.196.31.155:8080/media/documents/"
    username = TA.objects.all().filter(id = uid)[0].username
    examname = SubjectiveExam.objects.all().filter(id = eid)[0].name
    q = x+username+"_"+examname+"_"+str(index)
    mrm = SubjectiveExamTaken.objects.all().get(exam__id = eid, user__id = uid, q_index = index)
    if request.method == 'POST':
        form = SubjectiveExamTakenForm(request.POST, instance=mrm)
        if form.is_valid():
            exam = form.save(commit=False)
            exam.corrected_by = TA.objects.get(username = request.session['username'])
            exam.save()
            return HttpResponseRedirect('/ta/correct_exam/'+str(eid)+'/'+str(uid))
        else:
            return render(request, 'question.html', {'q':q, 'form': form})
    else:
        form = SubjectiveExamTakenForm(instance=mrm)
    return render(request, 'question.html', {'q':q, 'form':form, 'cb' : mrm.corrected_by})

eeeee/templates/edit_exam.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<style>
	input {
		border-radius: 5px;
	}
  body{
    background-color: #f9f6ed;
  }
  #id_name{
      width: 300px;
    }
    #id_start_time{
      width: 300px;
    }
    #id_end_time{
      width: 300px;
    }
</style>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark" style="color">
  <!-- Links -->
  <ul class="navbar-nav">
   <!-- Dropdown -->
    <li class="nav-item">
      <a class="nav-link" href="/instructor" style="color: white">Home</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" style="color: white">
        Create Exam
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="/instructor/new_exam">Objective</a>
        <a class="dropdown-item" href="/instructor/new_subjective_exam">Subjective</a>
      </div>
    </li>
    <li class="nav-item" style="margin-left: 1050px">
      <a class="nav-link" href="/instructor/logout" style="color: white">Logout</a>
    </li>
  </ul>
</nav>


<div class="container" align="center" style="margin-top: 50px;background-color: #edfaff;border-radius: 5px;padding: 30px">
  <h2 align="center">Edit your exam</h2>
  {% load bootstrap4 %}
<form method="post" style="margin-left: 200px; margin-right: 200px">
    {% csrf_token %}
    {% bootstrap_form form %}
    <!-- {{ form.as_p }} -->
    <button type="submit" class="btn btn-success"> Submit </button>
</form>
</div>

eeeee/templates/new_exam.html
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<title></title>
	<style type="text/css">
		input {
			border-radius: 5px;
		}
		body{
			background-color: #f9f6ed;
		}
		#id_name{
			width: 300px;
		}
		#id_start_time{
			width: 300px;
		}
		#id_end_time{
			width: 300px;
		}
		#id_qno{
			width: 300px;
		}
	</style>
</head>
 	<nav class="navbar navbar-expand-sm bg-dark navbar-dark" style="color">
	  <!-- Links -->
	  <ul class="navbar-nav">
	   <!-- Dropdown -->
	    <li class="nav-item">
	      <a class="nav-link" href="/instructor/topics_in_qb" style="color: white">Question Bank</a>
	    </li>
	    <li class="nav-item dropdown">
	      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" style="color: white">
	        Create Exam
	      </a>
	      <div class="dropdown-menu">
	        <a class="dropdown-item" href="/instructor/new_exam">Objective</a>
	        <a class="dropdown-item" href="/instructor/new_subjective_exam">Subjective</a>
	      </div>
	    </li>
	    <li class="nav-item" style="margin-left: 950px">
	      <a class="nav-link" href="/instructor/logout" style="color: white">Logout</a>
	    </li>
	  </ul>
	</nav>
	<div class="container" style="margin-top: 50px;background-color: #D3D3D3;border-radius: 5px;padding: 30px">
	<h2 align="center">Create new exam here</h2>
	<center>
	{% load bootstrap4 %}
	<form class="form" method="post">
	    {% csrf_token %}
	    {% bootstrap_form form %}
	    <button type="submit" class="btn btn-success"> Submit </button>
	</form>
	</center>
	<br>
</div>

eeeee/templates/newinstructor.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<style>
	input {
		border-radius: 5px;
	}
	body{
		background-color: #f9f6ed;
	}
	#id_username{
		width: 400px;
	}
	#id_password{
		width: 400px;
	}
	#id_first_name{
		width: 400px;
	}
	#id_last_name{
		width: 400px;
	}
	#id_email{
		width: 400px;
	}
	#id_department{
		width: 400px;
	}
	#id_course{
		width: 400px;
	}
</style>

<div class="container">
	<br>
<button type="button" class="btn btn-info"><a href="/" style="color:#FFFFFF;"> Back to Main Page </a></button>
<br><br>
<div align="center" style="background-color: #D3D3D3;border-radius: 10px; padding: 30px">
	{% load bootstrap4 %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-success"> Submit </button>
</form>
<br>
</div>
</div>

eeeee/templates/newstudent.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<style>
	input {
		border-radius: 5px;
	}
	body{
		background-color: #f9f6ed;
	}
	#id_username{
		width: 400px;
	}
	#id_password{
		width: 400px;
	}
	#id_first_name{
		width: 400px;
	}
	#id_last_name{
		width: 400px;
	}
	#id_email{
		width: 400px;
	}
	#id_department{
		width: 400px;
	}
	#id_course{
		width: 400px;
	}
</style>

<div class="container">
	<br>
<button type="button" class="btn btn-info"><a href="/" style="color:#FFFFFF;"> Back to Main Page </a></button>
<br><br>
<div align="center" style="background-color: #D3D3D3;border-radius: 10px; padding: 30px">
	{% load bootstrap4 %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-success"> Submit </button>
</form>
<br>
</div>
</div>

eeeee/templates/question.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<style>
	input {
		border-radius: 5px;
	}
	body{
		background-color: #f9f6ed;
	}
	#id_username{
		width: 400px;
	}
	#id_password{
		width: 400px;
	}
	#id_first_name{
		width: 400px;
	}
	#id_last_name{
		width: 400px;
	}
	#id_email{
		width: 400px;
	}
	#id_department{
		width: 400px;
	}
	#id_course{
		width: 400px;
	}
</style>

<div class="container">
    <br>
    <div align=center>
        <img src="{{q}}" alt="not uploaded" height="720" width="1280" style="transform: rotate(90deg);margin-top: 300px">
        </div>
    <br><br>
<div align="center" style="background-color: #D3D3D3;border-radius: 10px; padding: 30px; margin-top: 250px;margin-left: 280px;width: 720px;">
	{% load bootstrap4 %}
<form method="post">
        <br>
        <h6 align=left>Last corrected by : {{cb}}</h6 > 
        <br>
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-success"> Submit </button>
</form>
<br>
</div>
</div>


<!-- <form method="post" style="margin-top: 500px" align=center>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
    
</form> -->